-- Planned Investment Governance Schema
-- Schema: TEMP.INVESTMENT_GOVERNANCE

CREATE SCHEMA IF NOT EXISTS TEMP.INVESTMENT_GOVERNANCE;

-- Investment Requests table
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS (
    REQUEST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REQUEST_TITLE VARCHAR(500) NOT NULL,
    ACCOUNT_ID VARCHAR(50),
    ACCOUNT_NAME VARCHAR(500),
    
    -- Investment Details
    INVESTMENT_TYPE VARCHAR(100),
    REQUESTED_AMOUNT NUMBER(18,2),
    INVESTMENT_QUARTER VARCHAR(20),
    BUSINESS_JUSTIFICATION TEXT,
    EXPECTED_OUTCOME TEXT,
    RISK_ASSESSMENT TEXT,
    
    -- Requester Info
    CREATED_BY VARCHAR(255),
    CREATED_BY_NAME VARCHAR(255),
    CREATED_BY_EMPLOYEE_ID NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Organization Context
    THEATER VARCHAR(100),
    INDUSTRY_SEGMENT VARCHAR(100),
    
    -- Status and Workflow
    STATUS VARCHAR(50) DEFAULT 'DRAFT',
    CURRENT_APPROVAL_LEVEL NUMBER DEFAULT 0,
    NEXT_APPROVER_ID NUMBER,
    NEXT_APPROVER_NAME VARCHAR(255),
    NEXT_APPROVER_TITLE VARCHAR(255),
    
    -- Approval Chain (up to GVP)
    DM_APPROVED_BY VARCHAR(255),
    DM_APPROVED_AT TIMESTAMP_NTZ,
    DM_COMMENTS TEXT,
    RD_APPROVED_BY VARCHAR(255),
    RD_APPROVED_AT TIMESTAMP_NTZ,
    RD_COMMENTS TEXT,
    AVP_APPROVED_BY VARCHAR(255),
    AVP_APPROVED_AT TIMESTAMP_NTZ,
    AVP_COMMENTS TEXT,
    GVP_APPROVED_BY VARCHAR(255),
    GVP_APPROVED_AT TIMESTAMP_NTZ,
    GVP_COMMENTS TEXT,
    
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Linked Opportunities table
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.REQUEST_OPPORTUNITIES (
    LINK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REQUEST_ID NUMBER NOT NULL,
    OPPORTUNITY_ID VARCHAR(50) NOT NULL,
    LINKED_BY VARCHAR(255),
    LINKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (REQUEST_ID) REFERENCES TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(REQUEST_ID)
);

-- Contributors table (for suggested changes while in DRAFT)
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.REQUEST_CONTRIBUTORS (
    CONTRIBUTOR_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REQUEST_ID NUMBER NOT NULL,
    CONTRIBUTOR_USERNAME VARCHAR(255),
    CONTRIBUTOR_NAME VARCHAR(255),
    CAN_EDIT BOOLEAN DEFAULT FALSE,
    ADDED_BY VARCHAR(255),
    ADDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (REQUEST_ID) REFERENCES TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(REQUEST_ID)
);

-- Suggested Changes table (draft mode suggestions)
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.SUGGESTED_CHANGES (
    SUGGESTION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REQUEST_ID NUMBER NOT NULL,
    FIELD_NAME VARCHAR(100),
    SUGGESTED_VALUE TEXT,
    REASON TEXT,
    SUGGESTED_BY VARCHAR(255),
    SUGGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    REVIEWED_BY VARCHAR(255),
    REVIEWED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (REQUEST_ID) REFERENCES TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(REQUEST_ID)
);

-- Audit Log
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.AUDIT_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REQUEST_ID NUMBER,
    ACTION VARCHAR(50),
    OLD_VALUES VARIANT,
    NEW_VALUES VARIANT,
    PERFORMED_BY VARCHAR(255),
    PERFORMED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Users/Approvers table with hierarchy
CREATE OR REPLACE TABLE TEMP.INVESTMENT_GOVERNANCE.USERS (
    USER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SNOWFLAKE_USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMPLOYEE_ID NUMBER,
    DISPLAY_NAME VARCHAR(255),
    TITLE VARCHAR(255),
    ROLE VARCHAR(50),
    THEATER VARCHAR(100),
    INDUSTRY_SEGMENT VARCHAR(100),
    MANAGER_ID NUMBER,
    MANAGER_NAME VARCHAR(255),
    APPROVAL_LEVEL NUMBER,
    IS_FINAL_APPROVER BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes for performance
CREATE OR REPLACE INDEX IDX_REQUESTS_STATUS ON TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(STATUS);
CREATE OR REPLACE INDEX IDX_REQUESTS_THEATER ON TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(THEATER);
CREATE OR REPLACE INDEX IDX_REQUESTS_QUARTER ON TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(INVESTMENT_QUARTER);
CREATE OR REPLACE INDEX IDX_REQUESTS_CREATED_BY ON TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS(CREATED_BY);
CREATE OR REPLACE INDEX IDX_OPP_REQUEST ON TEMP.INVESTMENT_GOVERNANCE.REQUEST_OPPORTUNITIES(REQUEST_ID);
CREATE OR REPLACE INDEX IDX_CONTRIBUTORS_REQUEST ON TEMP.INVESTMENT_GOVERNANCE.REQUEST_CONTRIBUTORS(REQUEST_ID);
