-- Views for Investment Governance

-- View for timestamp tracking (cache freshness)
CREATE OR REPLACE VIEW TEMP.INVESTMENT_GOVERNANCE.VW_DATA_SOURCE_TIMESTAMPS AS
SELECT 'INVESTMENT_REQUESTS' AS DATA_SOURCE, MAX(UPDATED_AT) AS LAST_MODIFIED FROM TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS
UNION ALL
SELECT 'USERS' AS DATA_SOURCE, MAX(CREATED_AT) AS LAST_MODIFIED FROM TEMP.INVESTMENT_GOVERNANCE.USERS
UNION ALL
SELECT 'REQUEST_OPPORTUNITIES' AS DATA_SOURCE, MAX(LINKED_AT) AS LAST_MODIFIED FROM TEMP.INVESTMENT_GOVERNANCE.REQUEST_OPPORTUNITIES
UNION ALL
SELECT 'SUGGESTED_CHANGES' AS DATA_SOURCE, MAX(SUGGESTED_AT) AS LAST_MODIFIED FROM TEMP.INVESTMENT_GOVERNANCE.SUGGESTED_CHANGES;

-- View for current user info
CREATE OR REPLACE VIEW TEMP.INVESTMENT_GOVERNANCE.VW_CURRENT_USER_INFO AS
SELECT 
    u.USER_ID,
    u.SNOWFLAKE_USERNAME,
    u.EMPLOYEE_ID,
    u.DISPLAY_NAME,
    u.TITLE,
    u.ROLE,
    u.THEATER,
    u.INDUSTRY_SEGMENT,
    u.MANAGER_ID,
    u.MANAGER_NAME,
    u.APPROVAL_LEVEL,
    u.IS_FINAL_APPROVER
FROM TEMP.INVESTMENT_GOVERNANCE.USERS u
WHERE u.SNOWFLAKE_USERNAME = CURRENT_USER();

-- View for investment summary
CREATE OR REPLACE VIEW TEMP.INVESTMENT_GOVERNANCE.VW_INVESTMENT_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_REQUESTS,
    COUNT(CASE WHEN STATUS = 'DRAFT' THEN 1 END) AS TOTAL_DRAFT,
    COUNT(CASE WHEN STATUS IN ('SUBMITTED', 'DM_APPROVED', 'RD_APPROVED', 'AVP_APPROVED') THEN 1 END) AS TOTAL_SUBMITTED,
    COUNT(CASE WHEN STATUS = 'FINAL_APPROVED' THEN 1 END) AS TOTAL_APPROVED,
    COUNT(CASE WHEN STATUS = 'REJECTED' THEN 1 END) AS TOTAL_REJECTED,
    COALESCE(SUM(REQUESTED_AMOUNT), 0) AS TOTAL_INVESTMENT_REQUESTED,
    COALESCE(SUM(CASE WHEN STATUS = 'FINAL_APPROVED' THEN REQUESTED_AMOUNT ELSE 0 END), 0) AS TOTAL_INVESTMENT_APPROVED
FROM TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS;

-- View for pending approvals count per user
CREATE OR REPLACE VIEW TEMP.INVESTMENT_GOVERNANCE.VW_PENDING_MY_APPROVAL AS
SELECT
    NEXT_APPROVER_NAME,
    COUNT(*) AS PENDING_COUNT
FROM TEMP.INVESTMENT_GOVERNANCE.INVESTMENT_REQUESTS
WHERE STATUS IN ('SUBMITTED', 'DM_APPROVED', 'RD_APPROVED', 'AVP_APPROVED')
GROUP BY NEXT_APPROVER_NAME;

-- View for requests with linked opportunity details
CREATE OR REPLACE VIEW TEMP.INVESTMENT_GOVERNANCE.VW_REQUEST_OPPORTUNITIES AS
SELECT
    ro.LINK_ID,
    ro.REQUEST_ID,
    ro.OPPORTUNITY_ID,
    o.OPPORTUNITY_NAME,
    o.ACCOUNT_NAME,
    o.STAGE_NAME AS STAGE,
    o.AMOUNT,
    o.CLOSE_DATE,
    o.OWNER_NAME
FROM TEMP.INVESTMENT_GOVERNANCE.REQUEST_OPPORTUNITIES ro
LEFT JOIN SFDC_SHARED.SFDC_VIEWS.OPPORTUNITIES o ON ro.OPPORTUNITY_ID = o.OPPORTUNITY_ID;
